import Link from 'next/link';
import { ArrowRight, Check, Globe2, LogIn, ShieldCheck, Sparkles, Timer } from 'lucide-react';
import { SubtitleConverter } from '@/components/SubtitleConverter';
import { Button } from '@/components/ui/button';

const features = [
  ['Timestamp-safe output', 'Every cue, line break and timing marker remains exactly where it belongs.'],
  ['Sinhala with context', 'Dialogue is translated in batches so tone and meaning stay connected.'],
  ['A focused workflow', 'Upload, follow live progress, and download a ready-to-watch SRT file.'],
];

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden">
      <nav className="relative z-20 mx-auto flex h-20 w-full max-w-7xl items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-3" aria-label="SiSub home"><img src="/sisub-mark.svg" alt="SiSub" className="h-10 w-10 rounded-xl shadow-lg shadow-amber-400/10" /><span className="text-lg font-semibold tracking-tight text-white">SiSub<span className="text-amber-300">.</span></span></Link><div className="hidden items-center gap-7 text-sm text-slate-400 md:flex"><Link href="#studio" className="transition hover:text-white">Studio</Link><Link href="#workflow" className="transition hover:text-white">How it works</Link></div><Button asChild variant="ghost" className="text-slate-300 hover:bg-white/5 hover:text-white"><Link href="/login"><LogIn /> Sign in</Link></Button></nav>
      <section className="relative mx-auto max-w-7xl px-5 pb-20 pt-12 sm:px-8 md:pb-28 md:pt-20"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" /><div className="grid items-center gap-14 lg:grid-cols-[0.92fr_1.08fr] lg:gap-20"><div className="relative z-10"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-amber-300/20 bg-amber-300/10 px-3 py-1.5 text-xs font-medium text-amber-200"><Sparkles className="h-3.5 w-3.5" /> Sinhala subtitle studio</div><h1 className="max-w-3xl text-balance text-5xl font-semibold tracking-[-0.055em] text-white sm:text-6xl md:text-7xl">Every story deserves to feel <span className="text-gradient">local.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">Turn English SRT files into natural Sinhala subtitles while keeping the timing, pacing, and feeling of every scene intact.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Button asChild size="lg" className="h-12 rounded-xl bg-amber-300 px-6 font-semibold text-slate-950 shadow-xl shadow-amber-400/15 hover:bg-amber-200"><Link href="#studio">Open the studio <ArrowRight /></Link></Button><div className="flex items-center gap-2 px-2 text-sm text-slate-400"><ShieldCheck className="h-4 w-4 text-emerald-300" /> Keeps SRT structure intact</div></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-xs font-medium uppercase tracking-[0.15em] text-slate-500"><span className="flex items-center gap-2"><Timer className="h-4 w-4 text-amber-300" /> Live progress</span><span className="flex items-center gap-2"><Globe2 className="h-4 w-4 text-amber-300" /> Sinhala-first</span></div></div><div id="studio" className="relative z-10 scroll-mt-8"><SubtitleConverter /></div></div></section>
      <section id="workflow" className="border-y border-white/[0.07] bg-white/[0.025]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="eyebrow">Built for the final cut</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">A calmer subtitle workflow.</h2></div><p className="max-w-md text-sm leading-6 text-slate-400">No retiming, no manual copy-paste. SiSub respects the format your video player expects.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{features.map(([title, description], index) => <article key={title} className="premium-panel rounded-2xl p-7"><span className="mb-8 flex h-9 w-9 items-center justify-center rounded-lg bg-amber-300 text-sm font-bold text-slate-950">0{index + 1}</span><h3 className="text-lg font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p></article>)}</div></div></section>
      <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:items-center"><div className="subtitle-sample rounded-2xl border border-white/10 p-6 font-mono text-sm shadow-2xl sm:p-8"><p className="text-slate-600">124</p><p className="mt-2 text-slate-500">00:05:22,100 --&gt; 00:05:25,400</p><p className="mt-3 text-slate-300">I am so mad at you right now!</p><div className="my-7 h-px bg-white/10" /><p className="text-slate-600">124</p><p className="mt-2 text-amber-200/70">00:05:22,100 --&gt; 00:05:25,400</p><p className="mt-3 text-white">මට දැන් ඔයා එක්ක මාර තරහයි තියෙන්නේ!</p></div><div><p className="eyebrow">Meaning, not just words</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Translation that respects the scene.</h2><p className="mt-5 max-w-xl leading-7 text-slate-400">The conversion pipeline parses each subtitle block, translates contextual batches, and rebuilds the original SRT structure for an effortless hand-off.</p><ul className="mt-8 space-y-4 text-sm text-slate-300">{['Preserves indices, timestamps, style tags, and line breaks', 'Uses Gemini with a translation fallback pipeline', 'Streams conversion progress directly in the browser'].map(item => <li key={item} className="flex gap-3"><Check className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" />{item}</li>)}</ul></div></section>
      <footer className="border-t border-white/[0.07]"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-9 text-sm text-slate-500 sm:px-8 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-2"><img src="/sisub-mark.svg" alt="" className="h-6 w-6 rounded-md" /> SiSub — Sinhala Subtitle Studio</div><div className="flex gap-5"><Link href="/login" className="hover:text-white">Sign in</Link><a href="https://github.com/mr-kumuditha/Sinhala-Subtitle-Converter" className="hover:text-white">GitHub</a></div></div></footer>
    </main>
  );
}
